# Generated by Django 5.1 on 2024-09-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitId', models.CharField(default=None, editable=False, max_length=50, unique=True)),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryId', models.CharField(default=None, editable=False, max_length=50, unique=True)),
                ('Title', models.CharField(default=None, max_length=50)),
                ('ParentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(default=None, editable=False, max_length=50, unique=True)),
                ('Title', models.CharField(default=None, max_length=50)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField(null=True)),
                ('CategoryId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coefficient', models.IntegerField()),
                ('IsDefault', models.BooleanField(default=False)),
                ('IsPrimary', models.BooleanField(default=False)),
                ('ProductId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
                ('UnitId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.units')),
            ],
        ),
    ]
