# Generated by Django 5.1 on 2024-08-19 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(editable=False, max_length=50, unique=True)),
                ('FullName', models.CharField(blank=True, max_length=150, null=True)),
                ('NationalCode', models.CharField(max_length=15, unique=True)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Active', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(null=True)),
                ('UpdateAt', models.DateTimeField(null=True)),
                ('IsAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=80)),
                ('FlagId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.flag')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.access')),
                ('MenuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.menu')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
