# Generated by Django 5.1 on 2024-08-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_password_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='UrlPath',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
