# Generated by Django 5.1 on 2024-08-22 11:43

import django.db.models.deletion
import django_otp.plugins.otp_totp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_mytotpdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=django_otp.plugins.otp_totp.models.default_key, help_text='A hex-encoded secret key of up to 40 bytes.', max_length=80, validators=[django_otp.plugins.otp_totp.models.key_validator])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
