# Generated by Django 5.1 on 2024-08-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_passdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
